### ISSUE TITLE
Failed executions are not logged

### ISSUE THREAD

**Issue by fractaledmind** [basecamp/solid_queue#107]
I was trying to create a reproducible bug report script for this (which led to https://github.com/basecamp/solid_queue/pull/106), but in the meantime, let me just write this up. 

Nothing is logged when a job raises an exception. I tested this with a simple job:
```ruby
class RaisingJob < ApplicationJob
  def perform
    raise StandardError
  end
end
```

In the logs, all I see is:
```
20:43:35 queue.1 | [SolidQueue] Claimed 1 jobs
```

I can see the `SolidQueue::FailedExecution` object:
```
SolidQueue::FailedExecution.last
=>
#<SolidQueue::FailedExecution:0x0000000128493a58
 id: 17,
 job_id: 26,
 error:
  {"exception_class"=>"StandardError",
   "message"=>"StandardError",
   "backtrace"=>[...]},
 created_at: Sat, 30 Dec 2023 19:43:35.882895000 UTC +00:00>
```

**Comment by rosa** [comment]
Hey @fractaledmind, aren't these logged via Active Job's logger? I get this doing a similar test, with a job that raises: 
```
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a] Performing StoreResultJob (Job ID: 9f6ae83e-f908-47fb-a3b4-e372e4b2a77a) from SolidQueue(background) enqueued at 2024-01-01T11:41:37.871438000Z with arguments: 2, {:exception=>RuntimeError}
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   TRANSACTION (1.2ms)  BEGIN
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   ↳ app/jobs/store_result_job.rb:5:in `perform'
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   JobResult Create (2.8ms)  INSERT INTO `job_results` (`queue_name`, `status`, `value`, `created_at`, `updated_at`) VALUES ('background', 'started', '2', '2024-01-01 11:41:38.092244', '2024-01-01 11:41:38.092244')
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   ↳ app/jobs/store_result_job.rb:5:in `perform'
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   TRANSACTION (3.4ms)  COMMIT
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a]   ↳ app/jobs/store_result_job.rb:5:in `perform'
[ActiveJob] [StoreResultJob] [9f6ae83e-f908-47fb-a3b4-e372e4b2a77a] Error performing StoreResultJob (Job ID: 9f6ae83e-f908-47fb-a3b4-e372e4b2a77a) from SolidQueue(background) in 19.26ms: RuntimeError (RuntimeError):
/Users/rosa/Work/basecamp/solid_queue/test/dummy/app/jobs/store_result_job.rb:8:in `perform'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/execution.rb:69:in `block in _perform_job'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/execution.rb:68:in `_perform_job'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/instrumentation.rb:32:in `_perform_job'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/execution.rb:52:in `perform_now'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/instrumentation.rb:40:in `block in instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/notifications.rb:206:in `instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/instrumentation.rb:39:in `instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/instrumentation.rb:26:in `perform_now'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/logging.rb:18:in `block in perform_now'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/tagged_logging.rb:39:in `tagged'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/tagged_logging.rb:135:in `tagged'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/broadcast_logger.rb:212:in `method_missing'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/logging.rb:25:in `tag_logger'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/logging.rb:18:in `perform_now'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/execution.rb:30:in `block in execute'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/reloader.rb:77:in `block in wrap'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/reloader.rb:74:in `wrap'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.0/lib/active_job/execution.rb:28:in `execute'
/Users/rosa/Work/basecamp/solid_queue/app/models/solid_queue/claimed_execution.rb:49:in `execute'
/Users/rosa/Work/basecamp/solid_queue/app/models/solid_queue/claimed_execution.rb:29:in `perform'
/Users/rosa/Work/basecamp/solid_queue/lib/solid_queue/pool.rb:23:in `block (2 levels) in post'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/rosa/Work/basecamp/solid_queue/lib/solid_queue/app_executor.rb:7:in `wrap_in_app_executor'
/Users/rosa/Work/basecamp/solid_queue/lib/solid_queue/pool.rb:22:in `block in post'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/rosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```
This might be in `log/development.log` for you depending on how you have this configured. 

In any case, I still have this pending: https://github.com/basecamp/solid_queue/issues/103, which is kind of related.

**Comment by fractaledmind** [comment]
Hmm. I'll need to double check my ActiveJob logger. Sorry for the noise in that case. I've really enjoyed working with SolidQueue thus far, so thank you for the great library.

**Comment by rosa** [comment]
Oh, no worries at all, logging is not great right now. I definitely have to improve it.
