### ISSUE TITLE
undefined method `silence' for nil (NoMethodError) with latest rails main

### ISSUE THREAD

**Issue by dorianmariecom** [basecamp/solid_queue#168]
It happened between rails 917b6b2908510fbbc8d55db6360220485324e63c and rails 608c1bfe17a2626304b6aae96a3824517fc07bb2

```
07:00:38 web.1  | /Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/solid_queue-0.2.2/lib/solid_queue/processes/poller.rb:14:in `with_polling_volume': undefined method `silence' for nil (NoMethodError)
07:00:38 web.1  | 
07:00:38 web.1  |           ActiveRecord::Base.logger.silence { yield }
07:00:38 web.1  |                                    ^^^^^^^^
07:00:38 web.1  | 	from /Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/solid_queue-0.2.2/lib/solid_queue/dispatcher.rb:31:in `dispatch_next_batch'
07:00:38 web.1  | 	from /Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/solid_queue-0.2.2/lib/solid_queue/dispatcher.rb:22:in `run'
07:00:38 web.1  | 	from /Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/solid_queue-0.2.2/lib/solid_queue/processes/runnable.rb:48:in `block (2 levels) in do_start_loop'
```

**Comment by dorianmariecom** [comment]
It was because I had `config.active_record.logger = nil`

**Comment by jeremy** [comment]
Continued in #175
