### ISSUE TITLE
Code reload in development throws an error

### ISSUE THREAD

**Issue by morgoth** [basecamp/solid_queue#75]
When I try running solid queue locally in development evnironment it works fine.
I start worker by `rake solid_queue:start`
Then I change something in the code (in ApplicationJob class to be precise) and run some job without restarting the workers, the error is thrown:
```
/home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/worker.rb:35:in `block in poll': uninitialized constant SolidQueue::ReadyExecution (NameError)

          SolidQueue::ReadyExecution.claim(queues, pool.idle_threads, process.id)
                    ^^^^^^^^^^^^^^^^
Did you mean?  SolidQueue::FailedExecution
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/poller.rb:14:in `block in with_polling_volume'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/logger_silence.rb:18:in `block in silence'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/logger_thread_safe_level.rb:45:in `log_at'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/logger_silence.rb:18:in `silence'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/poller.rb:14:in `with_polling_volume'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/worker.rb:34:in `poll'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/worker.rb:19:in `run'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/runnable.rb:47:in `block in do_start_loop'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/runnable.rb:44:in `loop'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/runnable.rb:44:in `do_start_loop'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/runnable.rb:39:in `start_loop'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/processes/runnable.rb:13:in `start'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:123:in `block in start_fork'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:122:in `fork'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:122:in `start_fork'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:72:in `block in start_forks'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:72:in `each'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:72:in `start_forks'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:45:in `supervise'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:26:in `start'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/supervisor.rb:14:in `start'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solid_queue-0.1.1/lib/solid_queue/tasks.rb:4:in `block (2 levels) in <main>'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/bin/rake:25:in `load'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/bin/rake:25:in `<top (required)>'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:451:in `exec'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.1/exe/bundle:28:in `block in <top (required)>'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.1/exe/bundle:20:in `<top (required)>'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /home/wojtek/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[SolidQueue] Restarting fork[785525] (status: 1)
[SolidQueue] Starting Worker(pid=785589, hostname=arda, metadata={:polling_interval=>1, :queues=>"urgent,default", :thread_pool_size=>3})
[SolidQueue] Dispatched scheduled batch with 1 jobs
```

The jobs are still processed, however the error is thrown from time to time.

I believe it might be some issue with class reloading in development.
I'm using this config with Rails 7.1.2
```yaml
development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues:
        - urgent
        - default
      processes: 1
      threads: 3
      polling_interval: 1
```

**Comment by rosa** [comment]
Thank you, I'll look into it!
